language: node_js
node_js:
  - "14.5"
branches:
  only:
    - master
notifications:
  email: false
cache:
  directories:
  - node_modules
before_install:
- export TZ='Asia/Shanghai'
- export TRAVIS_TAG=$GIT_TAG
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - npm run build -- --prod  --base-href /ng-hello/
  - cp dist/ng-hello/index.html dist/ng-hello/404.html
  - tar -czvf dist.tgz ./dist/
  - sha256sum dist.tgz > dist.asc
deploy:
  - provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    keep_history: true
    local_dir: dist/ng-hello
    on:
      branch: master
  - provider: releases
    github_token: $GITHUB_TOKEN
    file:
    - dist.tgz
    - dist.asc
    skip_cleanup: true
    keep_history: true
    on:
      tags: true