language: node_js
node_js:
  - "14.5"
branches:
  only:
    - master
cache:
  directories:
  - node_modules
before_install:
- export TZ='Asia/Shanghai'
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master