language: node_js
node_js:
  - "14.0"
branches:
  only:
    - master
cache:
  directories:
  - node_modules
before_install:
- export TZ='Asia/Shanghai'
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  target-branch: gh-pages
  verbose: true
  on:
    branch: master